# External Ansible roles required by this repository

- src: openmicroscopy.analysis-tools
  version: 1.0.0

- src: openmicroscopy.basedeps
  version: 1.0.0

- src: openmicroscopy.cli-utils
  version: 1.0.0

- name: openmicroscopy.celery-docker
  src: https://github.com/manics/ansible-role-celery-docker.git
  version: devel

- src: openmicroscopy.docker
  version: 2.0.0

- src: openmicroscopy.docker-tools
  version: 1.0.0

- src: openmicroscopy.local-accounts
  version: 1.0.0

- src: openmicroscopy.logrotate
  version: 1.0.0

- src: openmicroscopy.lvm-partition
  version: 1.0.0

- src: openmicroscopy.nfs-mount
  version: 1.0.0

- src: openmicroscopy.nfs-share
  version: 1.0.0

- src: openmicroscopy.nginx
  version: 1.0.0

- src: openmicroscopy.nginx-proxy
  version: 1.0.0

- src: openmicroscopy.python-pydata
  version: 1.0.0

- src: openmicroscopy.redis
  version: 1.0.0

- src: openmicroscopy.samba-client
  version: 1.0.0

- src: openmicroscopy.selinux-utils
  version: 1.0.1

- src: openmicroscopy.sudoers
  version: 1.0.0

- src: openmicroscopy.upgrade-distpackages
  version: 1.0.0

- src: openmicroscopy.versioncontrol-utils
  version: 1.0.0

- name: openmicroscopy.prometheus-node
  src: https://github.com/manics/ansible-role-prometheus-node

- name: openmicroscopy.cadvisor
  src: https://github.com/manics/ansible-role-cadvisor
