---
# tasks file for roles/system-monitor-agent

- name: system packages | install epel repo
  become: yes
  yum:
    name: epel-release
    state: present

- name: system packages | check-mk agent
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - check-mk-agent
    - net-snmp
    - xinetd

- name: xinetd | start and enable
  become: yes
  service:
    enabled: yes
    name: xinetd.service
    state: started

- name: snmpd | start and enable
  become: yes
  service:
    enabled: yes
    name: snmpd.service
    state: started
