---
# Initial configuration of CI nodes
# Note you should reboot after changing the network configuration, and
# manually verify that the configuration is correct

- hosts: all
  roles:
  - role: openmicroscopy.upgrade-distpackages
  - role: openmicroscopy.network
