---
# Playbook for deploying Jenkins CI nodes

- hosts: ci-jenkins-linux
  roles:
    - role: openmicroscopy.jenkinsslave
    - role: openmicroscopy.sudoers
    - role: openmicroscopy.versioncontrol-utils
    - role: openmicroscopy.system-monitor-agent

# Deploy OMERO build and runtime prerequisites
- hosts: ci-omero
  roles:
    - role: openmicroscopy.omero-build
    - role: openmicroscopy.omero-runtime
#    - role: openmicroscopy.omero-build-cpp
    - role: openmicroscopy.postgresql
      postgresql_server_listen: "'*'"
      postgresql_server_auth:
      - database: all
        user: omero
        address: 0.0.0.0/0
      postgresql_users_databases:
      - user: omero
        password: omero
        databases: [omero]
      postgresql_server_chown_datadir: True

# Deploy prerequisites to build web apps
- hosts: ci-omero-web-apps-build
  roles:
    - role: openmicroscopy.omero-web-apps-build-dependencies

# Deploy OMERO build and runtime prerequisites
- hosts: ci-omero-web
  roles:
    - role: openmicroscopy.omero-runtime
    - role: openmicroscopy.omero-web-runtime
    - role: openmicroscopy.nginx


# Deploy Documentation prerequisites
- hosts: ci-docs
  roles:
    - role: openmicroscopy.sphinx-build
    - role: openmicroscopy.ansible
