---
# Playbook for provisioning Jenkins CI nodes

- hosts: ci-jenkins-linux
  roles:
  # Root LV Size 
  - role: openmicroscopy.lvm-partition
    lvm_lvname: root
    lvm_lvmount: /
    lvm_lvsize: "{{ provision_rootsize }}"
    lvm_lvfilesystem: "{{ provision_root_filesystem }}"
  # Jenkins work dir
  - role: openmicroscopy.lvm-partition
    lvm_lvname: jenkins-workdir
    lvm_lvmount: "{{ jenkinsworkdir }}"
    lvm_lvsize: "{{ jenkinssize }}"
  - role: openmicroscopy.sudoers
