---
# Playbook for initialising and preparing IDR openstack nodes.
# You may need to reboot after this

- hosts: idr-openstack

  roles:
  - role: openmicroscopy.upgrade-distpackages
  - role: openmicroscopy.server-swap
  - role: openmicroscopy.network
  - role: openmicroscopy.lvm-partition
    lvm_lvname: var_lib
    lvm_lvmount: /var/lib
    lvm_lvsize: 200G
    lvm_vgname: VGopenstack
    lvm_lvfilesystem: ext4
  - role: openmicroscopy.openstack-prepare

  vars:
    network_ifaces: "{{ pre_network_ifaces }}"

# You may wish to run idr-gpfs-client.yml
