---
# Playbook for provisioning QA Web nodes

- hosts: qa-web-linux
  roles:
    - role: openmicroscopy.postgresql
    - role: openmicroscopy.nginx
    - role: openmicroscopy.python-devel
    - role: openmicroscopy.openldap-devel
    - role: openmicroscopy.redis