---
- name: OME Website Setup
  hosts: web-linux # TODO?
  vars:
    ansible_user: centos

  roles:
    - role: openmicroscopy.versioncontrol-utils
    - role: openmicroscopy.jenkinsslave

- include: jekyll-playbooks/jekyll-deploy.yml
  tags: jekyll-deploy
