---
# Playbook for managing a docker instance in the
# openstack cloud.

- hosts: docker-hosts
  vars:
    ansible_user: centos
  roles:
  - role: openmicroscopy.storage-volume-initialise
    storage_volume_initialise_device: /dev/vdb
    storage_volume_initialise_mount: /var/lib/docker
  - role: openmicroscopy.basedeps
  - role: openmicroscopy.system-monitor-agent
  - role: openmicroscopy.versioncontrol-utils
  - role: openmicroscopy.docker
    docker_groupmembers: [centos]
  - role: openmicroscopy.sudoers
  - role: openmicroscopy.local-accounts
