---
# tasks file for roles/gridftp-ssh

- name: system packages | setup upstream Globus repo
  yum:
    name: http://toolkit.globus.org/ftppub/gt6/installers/repo/globus-toolkit-repo-latest.noarch.rpm
    state: present

- name: system packages | install gridftp
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - globus-gridftp
    - openssh-server
    - openssh-clients

- name:
  command: globus-gridftp-server-enable-sshftp
  args:
    creates: /etc/grid-security/sshftp
